name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build_image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
 
      - name: Build Docker Image
         run: docker build -t my-docker-image .
      - name: Tag Docker Image
         run: docker tag my-docker-image ${{ secrets.AWS_ECR_REGISTRY }}/my-docker-image:${{ github.sha }}
      - name: Push Docker Image to ECR
          run: docker push ${{ secrets.AWS_ECR_REGISTRY }}/my-docker-image:${{ github.sha }}
      - name: Cleanup Docker Images
         run: |
           # Define the number of images to keep (e.g., 5)
            keep_latest=5
            # Get the list of image digest IDs
            image_digests=$(aws ecr describe-images --repository-name my-docker-image --query 'imageDetails[*].[imageDigest]' --output json | jq -r '.[:'${keep_latest}'] | .[]')
            # Iterate over image digest IDs and delete old images
            for digest in ${image_digests}; do
              # Add the missing command here
              aws ecr batch-delete-image --repository-name my-docker-image --image-ids imageDigest=${digest}
            done
